const Produtos = [
    "Camiseta",
    "Calça Jeans",
    "Tênis Esportivo",
    "Relógio de Pulso",
    "Mochila",
    "Bola de Futebol",
    "Fone de Ouvido Bluetooth",
    "Óculos de Sol",
    "Câmera Digital",
    "Livro Best-Seller",
    "Console de Videogame",
    "Perfume de Luxo",
    "Colar de Diamantes",
    "Smartphone de Última Geração",
    "Tablet",
    "Cafeteira Automática",
    "Bicicleta de Montanha",
    "Violão Acústico",
    "Teclado Mecânico para Gaming",
    "Mala de Viagem",
    "Panela de Pressão Elétrica",
    "Relógio Inteligente",
    "Ventilador de Teto",
    "Caixa de Som Bluetooth",
    "Cadeira Ergonômica",
    "Aspirador de Pó Robô",
    "Máquina de Lavar Roupa",
    "Torradeira",
    "Liquidificador Multifuncional",
    "Monitor de 27 Polegadas",
    "Cadeira de Praia",
    "Relógio de Parede Decorativo",
    "Câmera de Segurança Wi-Fi",
    "Colchão Ortopédico",
    "Ferro de Passar a Vapor",
    "Chapinha de Cabelo Profissional",
    "Máquina de Cortar Cabelo",
    "Relógio de Mesa Clássico",
    "Cadeira de Escritório Ergonômica",
    "Jogo de Panelas Antiaderentes",
    "Batedeira Planetária",
    "Smart TV de 50 Polegadas",
    "Micro-ondas Inox",
    "Aparelho de Jantar Porcelana",
    "Tênis Casual",
    "Câmera Instantânea",
    "Ventilador de Teto",
    "Caixa de Som Bluetooth",
    "Cadeira Ergonômica",
    "Aspirador de Pó Robô",
    "Máquina de Lavar Roupa",
    "Torradeira",
    "Liquidificador Multifuncional",
    "Monitor de 27 Polegadas",
    "Cadeira de Praia",
    "Relógio de Parede Decorativo",
    "Câmera de Segurança Wi-Fi",
    "Colchão Ortopédico",
    "Ferro de Passar a Vapor",
    "Chapinha de Cabelo Profissional",
    "Máquina de Cortar Cabelo",
    "Relógio de Mesa Clássico",
    "Cadeira de Escritório Ergonômica",
    "Jogo de Panelas Antiaderentes",
    "Batedeira Planetária",
    "Smart TV de 50 Polegadas",
    "Micro-ondas Inox",
    "Aparelho de Jantar Porcelana",
    "Tênis Casual",
    "Câmera Instantânea",
    "Ventilador de Teto",
    "Caixa de Som Bluetooth",
    "Cadeira Ergonômica",
    "Aspirador de Pó Robô",
    "Máquina de Lavar Roupa",
    "Torradeira",
    "Liquidificador Multifuncional",
    "Monitor de 27 Polegadas",
    "Cadeira de Praia",
    "Relógio de Parede Decorativo",
    "Câmera de Segurança Wi-Fi",
    "Colchão Ortopédico",
    "Ferro de Passar a Vapor",
    "Chapinha de Cabelo Profissional",
    "Máquina de Cortar Cabelo",
    "Relógio de Mesa Clássico",
    "Cadeira de Escritório Ergonômica",
    "Jogo de Panelas Antiaderentes",
    "Batedeira Planetária",
    "Smart TV de 50 Polegadas",
    "Micro-ondas Inox",
    "Aparelho de Jantar Porcelana",
    "Tênis Casual",
    "Câmera Instantânea"
]

const filterA = (arr) => {
    arr.filter(item => item[0].toLocaleLowerCase === 'a')
}

//filter Produtos letra A
const filterOut = (arr) => {
    return arr.filter((item) => item[0].toLocaleLowerCase() === "a");
}

console.log(Produtos.filter((item) => item[0].toLocaleLowerCase() === "c"))

console.log(Produtos[0][0].toLocaleLowerCase() === "c")

console.log(Produtos.map(item => item))